# DHS Budget Explorer Data Schema Configuration
# This file defines all dimensions, data sources, and valid groupings

dimensions:
  # Core organizational dimension
  component:
    label: "Component"
    field: "component"
    type: "categorical"
    description: "DHS component or agency"
    # Alternative field names in different data sources
    alternate_fields:
      apportionment: "bureau"
    abbreviations:
      "Federal Emergency Management Agency": "FEMA"
      "U.S. Customs and Border Protection": "CBP"
      "U.S. Immigration and Customs Enforcement": "ICE"
      "Transportation Security Administration": "TSA"
      "United States Coast Guard": "USCG"
      "Cybersecurity and Infrastructure Security Agency": "CISA"
      "United States Secret Service": "USSS"
      "Citizenship and Immigration Services": "USCIS"
      "Federal Law Enforcement Training Center": "FLETC"
      "Science and Technology": "S&T"
      "Management Directorate": "MGMT"
      "Office of the Inspector General": "OIG"
      "Countering Weapons of Mass Destruction Office": "CWMD"
      "Analysis and Operations": "A&O"
      "Office of the Secretary and Executive Management": "OSEM"
  
  # Budget dimensions
  fund_type:
    label: "Fund Type"
    field: "fund_type"
    type: "categorical"
    description: "Type of funding (annual, no-year, etc.)"
    values:
      - "Annual"
      - "No-year"
      - "Multi-year"
      - "Trust fund"
      - "Revolving fund"
      - "Unknown"
  
  availability_type:
    label: "Availability Type"
    field: "availability_type"
    type: "categorical"
    description: "Period of fund availability"
    values:
      - "annual"
      - "no-year"
      - "multi-year"
  
  budget_category:
    label: "Budget Category"
    field: "budget_category"
    type: "categorical"
    description: "Budget category (discretionary, mandatory, etc.)"
    values:
      - "Discretionary"
      - "Mandatory"
      - "Unknown"
  
  # Spending dimensions
  spending_category:
    label: "Spending Category"
    field: "category"
    type: "categorical"
    description: "What the money is spent on"
    values:
      - "Personnel"
      - "Contracts & Services"
      - "Grants"
      - "Facilities"
      - "Supplies & Equipment"
      - "Travel"
      - "Other"
  
  object_class:
    label: "Object Class"
    field: "object_class_category"
    type: "categorical"
    description: "Detailed spending classification"
    parent: "spending_category"
  
  # Award dimensions
  award_type:
    label: "Award Type"
    field: "award_type"
    type: "categorical"
    description: "Type of contract or grant"
    
  award_category:
    label: "Award Category"
    field: "award_category"
    type: "categorical"
    description: "Contracts vs Assistance"
    values:
      - "Contracts"
      - "Assistance"
  
  awarding_office:
    label: "Awarding Office"
    field: "awarding_office"
    type: "categorical"
    description: "Office that awarded the contract/grant"
    filterable: true
    
  recipient_state:
    label: "State"
    field: "recipient_state"
    type: "categorical"
    description: "Recipient state"
    
  # Temporal dimension
  fiscal_year:
    label: "Fiscal Year"
    field: "fiscal_year"
    type: "temporal"
    format: "FY {value}"
    description: "Federal fiscal year"

# Data sources configuration
data_sources:
  apportionment:
    label: "Apportionment"
    description: "Congressional appropriations - what's approved"
    file: "processed_data/appropriations/dhs_budget_flat.json"
    value_fields:
      amount:
        label: "Amount"
        format: "currency"
    dimensions:
      - component
      - availability_type
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - availability_type
    default_grouping: "component"
    valid_groupings: ["component", "availability_type"]
    
  obligations:
    label: "Obligations"
    description: "Committed spending from USAspending"
    file: "processed_data/usaspending/spending_flat.json"
    value_fields:
      amount:
        label: "Obligations"
        format: "currency"
    dimensions:
      - component
      - spending_category
      - object_class
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - spending_category
    default_grouping: "component"
    valid_groupings: ["component", "spending_category"]
    
  outlays:
    label: "Outlays"
    description: "Actual payments from USAspending"
    file: "processed_data/usaspending/spending_flat.json"
    value_fields:
      amount:
        label: "Outlays"
        format: "currency"
    dimensions:
      - component
      - spending_category
      - object_class
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - spending_category
    default_grouping: "component"
    valid_groupings: ["component", "spending_category"]
    
  awards:
    label: "Awards & Contracts"
    description: "Contract and grant awards"
    file: "processed_data/usaspending/awards_flat.json"
    value_fields:
      obligations:
        label: "Award Amount"
        format: "currency"
      count:
        label: "Number of Awards"
        format: "number"
    dimensions:
      - component
      - award_type
      - award_category
      - awarding_office
      - recipient_state
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - award_type
      - award_category
      - recipient_state
    default_grouping: "component"
    valid_groupings: ["component", "award_type", "award_category", "recipient_state"]

# Valid dimension combinations for grouping
valid_groupings:
  # Single dimension
  - dimensions: ["component"]
    max_items: 20
    
  - dimensions: ["fund_type"]
    max_items: 10
    
  - dimensions: ["spending_category"]
    max_items: 10
    
  - dimensions: ["award_type"]
    max_items: 50
    
  # Two dimensions
  - dimensions: ["component", "fund_type"]
    max_items: 100
    
  - dimensions: ["component", "spending_category"]
    max_items: 150
    
  - dimensions: ["component", "award_type"]
    max_items: 500
    
  - dimensions: ["component", "recipient_state"]
    max_items: 1000
    
  - dimensions: ["award_type", "recipient_state"]
    max_items: 2000
    
  # Three dimensions (use with caution)
  - dimensions: ["component", "fund_type", "budget_category"]
    max_items: 200
    warning: "This grouping may create many small items"

# UI Configuration
ui_settings:
  treemap:
    min_label_width: 30
    min_label_height: 20
    min_value_height: 40
    padding: 2
    
  colors:
    scheme: "tableau20"
    by_dimension: "component"  # Which dimension determines colors
    
  tooltips:
    show_all_dimensions: true
    show_percentage: true
    show_rank: true
    
  animations:
    enabled: true
    duration: 750

# Export settings
export_formats:
  - csv
  - json
  - png