# DHS Budget Explorer Data Schema Configuration
# This file defines all dimensions, data sources, and valid groupings

# Display standardization settings
display_standards:
  # When to use abbreviations vs full names
  use_abbreviations_in:
    filters: false      # Use full names in filter dropdowns
    labels: true        # Use abbreviations in chart labels
    tables: true        # Use abbreviations in table displays
    tooltips: false     # Use full names in tooltips
  
  # Standardized value displays
  standardized_values:
    fund_type:
      "Annual": "Annual"
      "No-year": "No-Year"
      "Multi-year": "Multi-Year"
      "Trust fund": "Trust Fund"
      "Revolving fund": "Revolving Fund"
      "Unknown": "Unknown"
    availability_type:
      "annual": "Annual"
      "no-year": "No-Year"
      "multi-year": "Multi-Year"
    budget_category:
      "Discretionary": "Discretionary"
      "Mandatory": "Mandatory"
      "Unknown": "Unknown"

dimensions:
  # Core organizational dimension
  component:
    label: "Component"
    field: "component"
    type: "categorical"
    description: "DHS component or agency"
    # Alternative field names in different data sources
    alternate_fields:
      apportionment: "bureau"
    abbreviations:
      "Federal Emergency Management Agency": "FEMA"
      "U.S. Customs and Border Protection": "CBP"
      "U.S. Immigration and Customs Enforcement": "ICE"
      "Transportation Security Administration": "TSA"
      "United States Coast Guard": "USCG"
      "Cybersecurity and Infrastructure Security Agency": "CISA"
      "United States Secret Service": "USSS"
      "Citizenship and Immigration Services": "USCIS"
      "Federal Law Enforcement Training Center": "FLETC"
      "Federal Law Enforcement Training Centers": "FLETC"
      "Science and Technology": "S&T"
      "Management Directorate": "MGMT"
      "Office of the Inspector General": "OIG"
      "Countering Weapons of Mass Destruction Office": "CWMD"
      "Analysis and Operations": "A&O"
      "Office of the Secretary and Executive Management": "OSEM"
  
  # Budget dimensions
  fund_type:
    label: "Fund Type"
    field: "fund_type"
    type: "categorical"
    description: "Type of funding (annual, no-year, etc.)"
    values:
      - "Annual"
      - "No-Year"  # Standardized capitalization
      - "Multi-Year"  # Standardized capitalization
      - "Trust Fund"  # Standardized capitalization
      - "Revolving Fund"  # Standardized capitalization
      - "Unknown"
  
  availability_type:
    label: "Availability Type"
    field: "availability_type"
    type: "categorical"
    description: "Period of fund availability"
    values:
      - "Annual"  # Standardized to match fund_type
      - "No-Year"  # Standardized to match fund_type
      - "Multi-Year"  # Standardized to match fund_type
  
  budget_category:
    label: "Budget Category"
    field: "budget_category"
    type: "categorical"
    description: "Budget category (discretionary, mandatory, etc.)"
    values:
      - "Discretionary"
      - "Mandatory"
      - "Unknown"
  
  treasury_account:
    label: "Treasury Account (TAS)"
    field: "tas"
    type: "categorical"
    description: "Treasury Account Symbol"
  
  federal_account:
    label: "Federal Account"
    field: "account"
    type: "categorical"
    description: "Federal account name"
  
  # Spending dimensions
  spending_category:
    label: "Spending Category"
    field: "category"
    type: "categorical"
    description: "What the money is spent on"
    values:
      - "Personnel"
      - "Contracts & Services"
      - "Grants"
      - "Facilities"
      - "Supplies & Equipment"
      - "Travel"
      - "Other"
  
  object_class:
    label: "Object Class"
    field: "object_class_category"
    type: "categorical"
    description: "Detailed spending classification"
    parent: "spending_category"
  
  # Award dimensions
  award_type:
    label: "Award Type"
    field: "award_type"
    type: "categorical"
    description: "Type of contract or grant"
    
  award_category:
    label: "Award Category"
    field: "award_category"
    type: "categorical"
    description: "Contracts vs Assistance"
    values:
      - "Contracts"
      - "Assistance"
  
  awarding_office:
    label: "Awarding Office"
    field: "awarding_office"
    type: "categorical"
    description: "Office that awarded the contract/grant"
    filterable: true
    
  recipient_state:
    label: "State"
    field: "recipient_state"
    type: "categorical"
    description: "Recipient state"
    
  # Temporal dimension
  fiscal_year:
    label: "Fiscal Year"
    field: "fiscal_year"
    type: "temporal"
    format: "FY {value}"
    description: "Federal fiscal year"

# Data sources configuration
data_sources:
  apportionment:
    label: "Apportionment"
    description: "Congressional appropriations - what's approved"
    file: "processed_data/appropriations/dhs_budget_flat.json"
    value_fields:
      amount:
        label: "Amount"
        format: "currency"
    dimensions:
      - component
      - availability_type
      - fiscal_year
      - treasury_account
      - federal_account
      - fund_type
    filters:
      - fiscal_year
      - component
      - availability_type
      - fund_type
    default_grouping: "component"
    grouping_ui: "checkbox"  # Use checkboxes for multiple selection in explorer
    
  obligations:
    label: "Obligations"
    description: "Committed spending from USAspending"
    file: "processed_data/usaspending/spending_flat.json"
    value_fields:
      amount:
        label: "Obligations"
        format: "currency"
    dimensions:
      - component
      - spending_category
      - object_class
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - spending_category
    default_grouping: "component"
    grouping_ui: "checkbox"
    
  outlays:
    label: "Outlays"
    description: "Actual payments from USAspending"
    file: "processed_data/usaspending/spending_flat.json"
    value_fields:
      amount:
        label: "Outlays"
        format: "currency"
    dimensions:
      - component
      - spending_category
      - object_class
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - spending_category
    default_grouping: "component"
    grouping_ui: "checkbox"
    
  awards:
    label: "Awards & Contracts"
    description: "Contract and grant awards"
    file: "processed_data/usaspending/awards_flat.json"
    value_fields:
      obligations:
        label: "Award Amount"
        format: "currency"
    dimensions:
      - component
      - award_type
      - award_category
      - awarding_office
      - fiscal_year
    filters:
      - fiscal_year
      - component
      - award_type
      - award_category
    default_grouping: "component"

# Valid dimension combinations for grouping
valid_groupings:
  # Single dimension
  - dimensions: ["component"]
    max_items: 20
    
  - dimensions: ["fiscal_year"]
    max_items: 10
    
  - dimensions: ["fund_type"]
    max_items: 10
    
  - dimensions: ["treasury_account"]
    max_items: 200
    
  - dimensions: ["federal_account"]
    max_items: 50
    
  - dimensions: ["spending_category"]
    max_items: 10
    
  - dimensions: ["award_type"]
    max_items: 50
    
  # Two dimensions
  - dimensions: ["component", "fiscal_year"]
    max_items: 100
    
  - dimensions: ["fiscal_year", "component"]
    max_items: 100
    
  - dimensions: ["component", "fund_type"]
    max_items: 100
    
  - dimensions: ["fiscal_year", "fund_type"]
    max_items: 50
    
  - dimensions: ["component", "spending_category"]
    max_items: 150
    
  - dimensions: ["component", "award_type"]
    max_items: 500
    
  # Three dimensions (use with caution)
  - dimensions: ["component", "fund_type", "budget_category"]
    max_items: 200
    warning: "This grouping may create many small items"

# Analysis Configuration
analysis_settings:
  # Fiscal years for comparison
  comparison_years:
    current: 2025
    previous: 2023
    default: 2025  # Default year for filters
  
  # Available fiscal years for all tools
  available_fiscal_years: [2022, 2023, 2024, 2025]  # Years with data
  fiscal_year_labels:
    2022: "FY 2022"
    2023: "FY 2023"
    2024: "FY 2024"
    2025: "FY 2025"
  
  # Vendor analysis settings
  vendor_analysis:
    items_per_page: 50
    top_vendors_count: 50  # For treemap view
    top_growth_count: 50   # For top growth/decline views
    max_contracts_shown: 100  # Individual contracts in details
    max_products_shown: 10    # Product categories in details
    max_industries_shown: 5   # NAICS codes in details
    default_min_amount: 1000000  # Default minimum amount filter
  
  # Data processing settings
  data_processing:
    fiscal_years_to_load: ["FY2022", "FY2023", "FY2024", "FY2025"]  # Which years to process
    max_description_length: 500  # Truncate long descriptions
    aggregation_limit: 50000  # Max records before aggregation
  
  # Pagination settings
  pagination:
    default_page_size: 50
    max_page_size: 200
  
  # File naming patterns
  file_patterns:
    contracts: "*Contracts_AccountBreakdownByAward*.csv"
    assistance: "*Assistance_AccountBreakdownByAward*.csv"
    spending_tas: "*DHS_Spending_By_TAS*.csv"
  
  # Data quality settings
  data_quality:
    min_valid_amount: -1000000000  # Flag amounts below this as suspicious
    max_valid_amount: 100000000000  # Flag amounts above this as suspicious
    required_fields: ["fiscal_year", "component", "amount"]
  
  # Visualization settings
  visualization:
    color_scheme: "tableau20"  # D3 color scheme to use
    treemap_padding: 2
    treemap_min_label_width: 30
    treemap_min_label_height: 20
    chart_margins:
      top: 40
      right: 120
      bottom: 60
      left: 80
  
  # Display formats
  display_formats:
    fiscal_year_format: "FY {year}"  # How to display fiscal years
    fiscal_year_sort: "ascending"    # Sort years oldest to newest
    currency_precision:
      billions: 2  # Decimal places for billions
      millions: 2  # Decimal places for millions
      thousands: 0 # Decimal places for thousands
      
# Component Display Settings
component_display:
  use_abbreviations: true  # Use abbreviated names where possible
  standardize_names: true  # Ensure consistent naming across all tools
  
# UI Configuration
ui_settings:
  treemap:
    min_label_width: 30
    min_label_height: 20
    min_value_height: 40
    padding: 2
    
  colors:
    scheme: "tableau20"
    by_dimension: "component"  # Which dimension determines colors
    
  tooltips:
    show_all_dimensions: true
    show_percentage: true
    show_rank: true
    
  animations:
    enabled: true
    duration: 750

# Export settings
export_formats:
  - csv
  - json
  - png
  
# Error handling
error_handling:
  show_warnings: true
  max_retries: 3
  continue_on_error: true  # Continue processing even if some files fail