name: Update SF133 Data

on:
  # Run on push to main
  push:
    branches: [ main ]
  # Run on schedule (e.g., monthly)
  schedule:
    - cron: '0 0 1 * *'  # First day of each month
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download and process SF133 data
      run: python3 main.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/all_agencies_summary.json data/all_agencies_obligation_summary.csv
        git diff --staged --quiet || git commit -m "Update SF133 data"
        git push